### ISSUE TITLE
Create CR Checklist

### ISSUE THREAD

**Issue by ajaygandecha** [unc-csxl/csxl.unc.edu#440]
This ticket aims to create a checklist to run through when completing code reviews.

**Comment by ajaygandecha** [comment]
**0. Design Document Review**
- [ ] Clear use case is defined.
- [ ] Entity diagrams are defined.
- [ ] Plan for frontend design is discussed.

**1. Backend Entities and Models Review**
- [ ] Ensure that the `backend.script.create_database` and `backend.script.reset_demo` scripts run as expected.
- [ ] Ensure that all entities are fully documented.

**2. Backend Services and API Review**
- [ ] All basic CRUD functionality has been provided.
- [ ] Integrate pagination where the length of the average expected output exceeds 50.
- [ ] Permissions are enforced on service functions where necessary.
- [ ] Service functions are entirely documented with Python docstrings provided.
- [ ] Unit tests have been written for every new service function, *and* test coverage for the feature is at 100%.
- [ ] All APIs run as expected from the `/docs` URL.
- [ ] APIs are entirely documented with Python docstrings provided.
- [ ] Correct models are returned, and sensitive data is not accidentally exposed.

**3. Frontend Review**
- [ ] The new frontend service should include all necessary endpoints for the feature.
- [ ] All service methods return observables where needed.
- [ ] Angular Signals are used to store an internal reactive data store, where needed. (Replacement of `RxObject`)
- [ ] Service is fully documented with TS docstrings.
- [ ] Models are placed in a `feature.model.ts` file.
- [ ] New components should be declared in a feature module.
- [ ] Component HTML utilizes the new `@` standard (instead of the directives `ngIf`, `ngFor`, etc).

**Comment by ajaygandecha** [comment]
@jadekeegan // @KrisJordan closing this ticket, I think this can morph into a larger discussion if COMP 393 or COMP 523 groups spring up in the future!
