### ISSUE TITLE
Implement Digital Signage for the XL Lounge

### ISSUE THREAD

**Issue by ajaygandecha** [unc-csxl/csxl.unc.edu#596]
## Synopsis

With the new renovations, the XL hallway now has a large 65" display. These displays should be driven by special routes on the XL web application that integrate with our API and provide live, up-to-date information about XL availability, upcoming events, new articles, interesting statistics, the XL Instagram feed, etc. It is likely that the frontend for this may have to be in a slimmed down Angular application separate from the CSXL repo. We can connect to the same CSXL backend, but the frontend may just be a single page application. This helps for a few reasons:
* Less bundle size, allowing the TV to load the website properly.
* The navigation is simplified, so you can full-screen the page without worrying about the sidebar.

***Your mission, should you choose to accept it, is to implement the page (and potentially the new repo) for the live display of the XL site***.

## Acceptance Criteria

*Note: Below is an iterated version of the COMP 423 final project criteria from the Spring 2024 semester.*

- [x] Show upcoming events, including "featured" events (see the code in the events service for details on what qualifies as a featured event)

- [x] Show stats on the XL, including current coworking status (both drop-in and room reservations). Stats on office hours may also be cool!

- [x] Show latest news articles or announcements.

- [x] (Potentially ??) show a leaderboard for XL drop-ins.

- [ ] ~~Show the XL Instagram feed. For Instagram Dispaly API integration, to pull the latest post(s) see: https://developers.facebook.com/docs/instagram-basic-display-api/overview. Additionally, look toward the GitHub API integration on the user profile page for linking to GitHub. How to store keys necessary for integration with this API (whether as an environment variable or in the database) is a challenge left to the project team.~~ *Note: The development team is __NOT__ considering this as of 11/5/24*

## First Steps

If your team chooses to accept this, please list yourself as "assignees" to this ticket! Then, begin to work on a backend entity diagram design and a frontend design on Figma. Then, comment them here on this ticket for approval! From there, you can begin creating a branch for this feature.

**NOTE: This is a frontend-heavy project - the frontend design process and review will be more meticulous!**

*If you need to create a new repo, reach out to @KrisJordan!*

For approvals, we will work in this order:
1. **Backend Review:** Tests to ensure your backend is working properly.
2. **Frontend Review:** Ensures your frontend looks good!

For tips on what we will look for, check out the [Contributing Guidelines](https://github.com/unc-csxl/csxl.unc.edu/blob/main/CONTRIBUTING.md).

**Comment by ItIsAndrewL** [comment]
# Possible Plan for development

The plan for development will start on the backend before moving to the frontend as we will need to create some custom routes to expose the information that we will need. This approved figma design is what we are going for on the frontend:

## Backend
Create two backend routes `/api/signage/fast` and `api/signage/slow` that exposes all the data we need for the tv so we only need to run one of these API route to populate all the data on the tv. 

The reason we would want to split it up into two different API calls is so the information that needs to be updated quickly, such as Occupancy, Leaderboard, and Office-hours can be queried more often than the info that doesn't change as often, such as the News and Upcoming events.

The `/api/signage/fast` route should expose the following data:

- [ ] Seat Availability
- [ ] Room Availability
- [ ] Check-in Leaderboard (pending Kris' approval)
- [ ] Office Hours Information

The `/api/signage/slow` route should expose this data:

- [ ] News article to display
- [ ] Upcoming Event(s) to display

## Frontend

Use already existing widgets/cards (possibly as reference as we may need to change core functionality) to implement the following:

- [ ] Occupancy
- [ ] News
- [ ] Upcoming Events

Create new card widgets for the following

- [ ] Check-in Leaderboard
- [ ] Office Hours

Additional Frontend Concerns

- [ ] Get the date to update + add "th", "nd", "st" to the day number
- [ ] Use a weather API to display the current weather

**Comment by ItIsAndrewL** [comment]
## Updates Moving into Spring 25 Semester

We are almost done with the signage. Over winter break I was able to complete the office hours widget complete with lazy loading of events to prevent unannounced refreshes and robustly tested on the frontend. Otherwise, the team has completed the coworking and rooms widget.

## TODO:

- [ ] Add pagination to the leaderboard so we can display 6-10 in a separate view
- [ ] Pagination for upcoming events
- [ ] Pagination for news
- [ ] Have the date/time update in real time
- [ ] Weather via external API
- [ ] Adding announcements

**Comment by ItIsAndrewL** [comment]
One question for @ajaygandecha. How should we go about differentiating the different COMP590s in the office hours display? I'm a little lost as to if we should list sections (but then some office hours have multiple sections?), or if it's expected for the 590s to have different titles somewhere.

**Comment by ajaygandecha** [comment]
@ItIsAndrewL ah, this is a great point - I assume there is not space for writing something like `COMP 590 (ProfLastName)` right?

**Comment by ItIsAndrewL** [comment]
@ajaygandecha not with the current spacing I have. Here's an example with some generated sample data from chat that shows the amount of space pretty well.
![image](https://github.com/user-attachments/assets/9b5c1b2e-717b-4747-bf81-37cbd232a121)
Of course, we will be using course codes (currently what I'm using for course name is the name entered when an instructor creates the office hours page on the MyCourses page) and the room numbers will be shorter. I do like this suggestion and I'll give it a try. I am concerned if the instructors last name is too long though. I may need to use ellipses in that case and I'm not sure how that would fly with all professors

**Comment by ajaygandecha** [comment]
Hmm, wondering if just plain section number would work - its length is more predictable, also in the case where two instructors are teaching different sections of the same course (for example, with 550 this sem), they might hold separate office hours, so having a section # might be the most flexible for the different edge cases - thoughts @ItIsAndrewL

**Comment by ItIsAndrewL** [comment]
This was what I was originally thinking about doing @ajaygandecha. However, some office hours sections on the MyCourses page can be for multiple sections so I'm not sure what to do in this scenario. Maybe grab the lowest section number and if it's section 001, then I don't display it?
